### ISSUE TITLE
Wrong Ram Info

### ISSUE THREAD

**Issue by gopar** [Phundrak/eshell-info-banner.el#17] opened 2021-12-30 06:33 UTC
Not sure what info you need from me to properly debug this :)
Also, mac has 16 GB available

![Screen Shot 2021-12-29 at 10 31 12 PM](https://user-images.githubusercontent.com/1545083/147727379-74b463a9-7881-420a-ac0d-936a4239c606.png)

**Comment by Phundrak** [comment] 2021-12-30 13:26
That’s quite the error indeed. It should be relatively easy to debug
though, I’ll investigate it soon. It seems there is also an issue with
the length of the ramp.

--
Lucien “Phundrak” Cartier-Tilet

<https://phundrak.com> (Français)

<https://phundrak.com/en> (English)

Sent from GNU/Emacs

**Comment by Phundrak** [comment] 2021-12-30 23:16
I cannot reproduce this issue on my macOS VM. This might be due to my
VM being stiill under macOS Catalina (by the way, I just found a bug
related to version detection, I’ll work on that in the meantime).
Could you give me the output of the following two shell commands on
your machine?

$ sysctl hw.physmem
$ sysctl hw.usermem

As well as the output of the following Elisp code?

(message "%s" system-type)

--
Lucien “Phundrak” Cartier-Tilet
<https://phundrak.com> (Français)
<https://phundrak.com/en> (English)
Sent from GNU/Emacs

**Comment by gopar** [comment] 2021-12-31 00:04
```shell
$ sysctl hw.physmem
hw.physmem: 2147483648

$ sysctl hw.usermem
hw.usermem: -722436096

$ (message "%s" system-type)
darwin
```

**Comment by Phundrak** [comment] 2021-12-31 13:30
It seems like physmem and usermem got broken in Big Sur. A new
implementation of retrieving RAM info needs to be implemented for
macOS.

For the record, neofetch does it like so:
,----
| mem_total="$(($(sysctl -n hw.memsize) / 1024 / 1024))"
| mem_wired="$(vm_stat | awk '/ wired/ { print $4 }')"
| mem_active="$(vm_stat | awk '/ active/ { printf $3 }')"
| mem_compressed="$(vm_stat | awk '/ occupied/ { printf $5 }')"
| mem_compressed="${mem_compressed:-0}"
| mem_used="$(((${mem_wired//.} + ${mem_active//.} + ${mem_compressed//.}) * 4 / 1024))"
`----

This could be a starting point for a patch.

--
Lucien “Phundrak” Cartier-Tilet

<https://phundrak.com> (Français)

<https://phundrak.com/en> (English)

Sent from GNU/Emacs

**Comment by Phundrak** [comment] 2022-01-04 18:52
@gopar I pushed a fix on the branch https://github.com/Phundrak/eshell-info-banner.el/tree/fix/macos-ram-detection, could you test it and see if it works as intended?

**Comment by gopar** [comment] 2022-01-04 18:58
it works!
![Screen Shot 2022-01-04 at 10 56 55 AM](https://user-images.githubusercontent.com/1545083/148109816-68214279-40ae-4dac-9906-ed11bf5534d9.png)

**Closed** 2022-01-04 19:01 UTC
Labels: bug, good first issue

**Comment by Phundrak** [comment] 2022-01-04 19:02
Perfect, it’s now merged in main!

--
Lucien “Phundrak” Cartier-Tilet

<https://phundrak.com> (Français)

<https://phundrak.com/en> (English)

Sent from GNU/Emacs
